[build]
	command = "yarn build"
	publish = "public"
	functions = "functions"

[build.environment]
	HUGO_VERSION = "0.47.1"

[context.production.environment]
	HUGO_ENV = "production"
	NODE_ENV = "production"

[context.deploy-preview]
	command = "yarn build:preview"

[[redirects]]
  from = "/agastya/sla"
  to = "/policies/sla/"

[[redirects]]
  from = "/agastya/*"
  to = "/platform/agastya/:splat"

[[redirects]]
  from = "/shravan/*"
  to = "/platform/shravan/:splat"

[[redirects]]
  from = "/valmiki/*"
  to = "/platform/valmiki/:splat"

[[redirects]]
  from = "/education"
  to = "/values/education/"

[[redirects]]
  from = "/environment"
  to = "/values/environment/"

[[redirects]]
  from = "/accessibility"
  to = "/values/accessibility/"

[[redirects]]
  from = "/justice"
  to = "/values/justice/"

[[redirects]]
  from = "/cookies"
  to = "/policies/cookies/"

[[redirects]]
  from = "/terms"
  to = "/policies/terms/"

[[redirects]]
  from = "/logos"
  to = "/press/logos/"

[[redirects]]
  from = "/brand-guidelines"
  to = "/press/brand-guidelines/"

[[redirects]]
  from = "/spaces"
  to = "/accelerator/spaces/"

[[redirects]]
  from = "/partners"
  to = "/accelerator/partners/"