[build]
	command = "yarn build"
	publish = "public"
	functions = "functions"

[build.environment]
	HUGO_VERSION = "0.47.1"

[context.production.environment]
	HUGO_ENV = "production"
	NODE_ENV = "production"

[context.deploy-preview]
	command = "yarn build:preview"

[[redirects]]
  from = "/agastya/*"
  to = "/platform/agastya/:splat"

[[redirects]]
  from = "/shravan/*"
  to = "/platform/shravan/:splat"

[[redirects]]
  from = "/valmiki/*"
  to = "/platform/valmiki/:splat"